apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  labels:
    app: api-gateway

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
