apiVersion: apps/v1
kind: Deployment

metadata:
  name: visits-service
  labels:
    app: visits-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: visits-service

  template:
    metadata:
      labels:
        app: visits-service

    spec:
      containers:
        - name: visits-service
          image: visits-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: SERVER_PORT
              value: "8080"

            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
